### ISSUE TITLE
Canparse incompatible with ISO-8859-1 DBC files

### ISSUE THREAD

**Issue by TGMaker** [jmagnuson/canparse#8]
I ran into some issues using canparse. After some debugging I found out that it can't parse dbc files in iso-8859-1 encoding. You get this kind of encoding as soon as you use characters like ° (for temperature).

Line 65 in pgn.rs gives an Err(..) back when an not UFT-8 is included in the read line

**Comment by jmagnuson** [comment]
Interesting, thanks for the notice-- I have only ever worked in UTF-8 but agree that other encodings could definitely be supported as well.

**Comment by TGMaker** [comment]
To convert it to UTF-8 helped. But then the program bugged out on a later stage in the file. I line 68 in pgn.rs with Err` value: ParseIntError { kind: InvalidDigit }'

The responsible line is the middle one. 
BA_ "VNSigAllNodes" SG_ 160 StWhlAngChksm 1;
BA_ "SignalLongName" SG_ 160 StWhlAngChksm "Steering Wheel Angle Checksum";
BA_ "SignalType" SG_ 160 StWhlAngChksm "UNM";

When is parse it it finds a entry which looks like this an crashes: 
SignalDefinition(SignalDefinition{start_bit:140737331213568, bit_len:33, little_endian:false, signed:true, scale:0.0000000000000000000000000000000000000000000126116862, offset:0, min_value:0.0000000000000000000000000000000000000000000140129846, max_value:0, units:None, receiving_node:None})

Did you ever tryout your parser with a dbc file created with Vector CANDB++ ?

**Comment by photex** [comment]
Howdy! Just ran into the same issue attempting to load a DBC which was created by a German company and so this crate was unable to parse it, failing with the same error (not utf-8) due to some identifiers and string content containing umlauts and so on.

**Comment by photex** [comment]
Encoding of this file is reported as: `ISO-8859 text, with very long lines, with CRLF line terminators`.

Worth noting this was also created by the Vector tools.

**Comment by jmagnuson** [comment]
So the ISO-8859-1 issue should be a pretty quick fix, I can get that out soon.

The `ParseIntError` may require some rework and possible API breakage, due to how the library is currently abstracted. But I've wanted to make this crate more generic anyway, so some amount of breakage is inevitable. Thanks for the reports!

**Comment by photex** [comment]
:+1: Seems to work for me so far.

**Comment by TGMaker** [comment]
I can also confirm that the issue with parsing an ISO-8859-1 file is fixed. Thank you very much for the fix :). 

Do you want a new issue for the other error?

**Comment by jmagnuson** [comment]
Awesome, I'll go ahead and merge.

>Do you want a new issue for the other error?

Sure, thanks. I've started on it already but would be good for tracking purposes.
